"""initial_schema

Revision ID: f843d0f73d7a
Revises: 
Create Date: 2025-11-09 21:28:45.550381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f843d0f73d7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('sector_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('class_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_circuit', 'sessions', ['circuit_id'], unique=False)
    op.create_index('idx_sessions_datetime', 'sessions', ['datetime'], unique=False)
    op.create_table('laps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_time', sa.Integer(), nullable=True),
    sa.Column('sector1_time', sa.Integer(), nullable=True),
    sa.Column('sector2_time', sa.Integer(), nullable=True),
    sa.Column('sector3_time', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_laps_session', 'laps', ['session_id'], unique=False)
    op.create_table('telemetry_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lap_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('throttle', sa.Float(), nullable=True),
    sa.Column('brake', sa.Float(), nullable=True),
    sa.Column('clutch', sa.Float(), nullable=True),
    sa.Column('steering_angle', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.Column('engine_temp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_lap', 'telemetry_points', ['lap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telemetry_lap', table_name='telemetry_points')
    op.drop_table('telemetry_points')
    op.drop_index('idx_laps_session', table_name='laps')
    op.drop_table('laps')
    op.drop_index('idx_sessions_datetime', table_name='sessions')
    op.drop_index('idx_sessions_circuit', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('vehicles')
    op.drop_table('circuits')
    # ### end Alembic commands ###
