project_id: "lfs-ayats"
api_token_env: "CROWDIN_API_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true
pull_request_title: "[i18n] Noves traduccions des de Crowdin"

files:
  - source: "/i18n/locales/en/*.json"
    translation: "/i18n/locales/%two_letters_code%/%original_file_name%"
  
  - source: "/docs/en/*.md"
    translation: "/docs/%two_letters_code%/%original_file_name%"

commit_message: "Noves traduccions %two_letters_code%"
export_only_approved: false
