# Vocabulari bàsic per a Vale
# Aplica només suggeriments d'ortografia terminològica.
extends: substitution
message: 'Preferència de terme: "%s"'
ignorecase: true
level: suggestion
scope: text
swap:
  # exemples de preferències
  registro: Log
  registre: Log
